theme: jekyll-theme-tactile
title: European Football League Predictor
description: Top European football league predictions using machine learning 
defaults:
  - scope:
      path: "/Home/"
      type: "pages"
    values:
      layout: "page"  # You can use "page" or another layout you prefer

   
